
#
# This LookML file was generated by AtScale on 2026-10-07T05:07:27.530770578Z
#
# AtScale version: 2026.8.0
# Catalog: internet_sales_catalog_Snowflake

connection: "atscale_az"
label: "internet_sales_catalog_Snowflake"


include: "/views/internet_sales_catalog_Snowflake/internet_sales.view.lkml"

include: "/views/internet_sales_catalog_Snowflake/internet_sales_no_pii.view.lkml"


explore: internet_sales {
  label: "internet_sales"
}

explore: internet_sales_no_pii {
  label: "internet_sales_no_pii"
}

